server:
  port: 8080
spring:
  application:
    name: maintenance
  datasource:
    url: jdbc:postgresql://localhost:5444/db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update



